[package]
name = "spring-batch-rs"
version = "0.1.4"
edition = "2021"
authors = ["Simon Boussekeyt <sboussekeyt@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sboussekeyt/spring-batch-rs"
documentation = "https://docs.rs/spring-batch-rs"
keywords = ["batch", "csv", "data", "json"]
readme = "README.md"
description = "A toolkit for building enterprise-grade batch applications"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[lib]
name = "spring_batch_rs"
path = "src/lib.rs"

[dependencies]
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.51"
csv = { version = "1.3.0", optional = true }
fake = { version = "2.9.2", features = ["time"], optional = true }
rand = { version = "0.8.5", optional = true }
time = { version = "0.3.31", features = ["serde-human-readable"], optional = true }
serde_json = { version = "1.0.108", optional = true }

[dev-dependencies]
spring-batch-rs = { path = ".", features = ["tests-cfg"] }
rand = { version = "0.8.5" }
mockall = "0.12.1"

[features]
# Include nothing by default
default = []
tests-cfg = ["full"]

# enable everything
full = [
  "csv",
  "json",
  "logger",
  "fake",
]

csv = ["dep:csv"]
json = ["dep:serde_json"]
time = ["dep:time"]
logger = []
fake = ["dep:fake", "dep:rand", "dep:time"]

[[example]]
name = "generate_csv_file_from_json_file_with_processor"

[[example]]
name = "generate_json_file_from_csv_string_with_fault_tolerance"

[[example]]
name = "generate_json_file_from_fake_persons"

[[example]]
name = "generate_csv_file_without_headers_from_fake_persons"
